name: flutter_master
description: Flutter Repository that contains best practice that I have come up with
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.2.1
  hive_flutter: ^1.1.0
  injectable: ^2.3.5
  intl: ^0.19.0
  provider: ^6.1.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  http_mock_adapter: ^0.6.1
  injectable_generator: ^2.5.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
